[package]
authors = ["panicbit <panicbit.dev@gmail.com>"]
name = "aoc"
version = "0.1.0"

[dependencies]
cachedir = "0.1.1"
chrono-tz = "0.5.0"
clap = "2.32.0"
failure = "0.1.3"
itertools = "0.7.9"
lazy_static = "1.2.0"
reqwest = "0.9.5"
select = "0.4.2"
serde = "1.0.80"
serde_derive = "1.0.80"
structopt-derive = "0.2.13"
open = "1.2.2"
aoc_codegen = { path = "aoc_codegen" }

[dependencies.chrono]
features = ["serde"]
version = "0.4.6"

[dependencies.preferences]
git = "https://github.com/Eh2406/preferences-rs"
rev = "4f426cf"
version = "2.0.0"
